### PR TITLE
ARM: tegra: lenovo-a2109a: Fix volume down and up keys switched

### PR DESCRIPTION
**Pull request by KaiJan57**

### CODE REVIEW

**Comment by digetx** [comment]
Thanks!

**Comment by KaiJan57** [comment]
Is there any chance to get HDMI audio working without codec driver, btw?

**Comment by digetx** [comment]
No, only codec method is supported by the upstream kernel. Do you have any problems with it?

**Comment by KaiJan57** [comment]
I hoped that sound over HDMI was not related to the codec IC, but as it is, there unfortunately is no sound even when using HDMI.

**Comment by digetx** [comment]
I'm recalling that @pgwipeout was saying that HDMI codec needs to be explicitly whitelisted for pulseaudio, maybe this is the problem.

**Comment by KaiJan57** [comment]
Interesting, do you know how, or could you point me to a guide?

**Comment by digetx** [comment]
I don't, but maybe @pgwipeout could.

**Comment by pgwipeout** [comment]
Apologies for the late response @KaiJan57.
You have to use alsamixer and make sure the hdmi sink is unmuted.
Use `speaker-test -Dhw:0,3 -c 2` to send a test audio stream to the device.
For pulseaudio add `load-module module-alsa-sink device=hw:0,3` to `/etc/pulse/default.pa`.

**Comment by KaiJan57** [comment]
Thank you very much, I will give that a try soon. No need to apologize :)

**Comment by KaiJan57** [comment]
Does not seem to work on my device, alsamixer returns:
Mixer attach default error: No such file or directory
Am I missing some kernel module maybe?

**Comment by pgwipeout** [comment]
Ensure CONFIG_SND_HDA_TEGRA is either built in or loaded as a module.
Also ensure it's enabled in your device tree.

**Comment by KaiJan57** [comment]
Yep, hda was missing in device tree. Now its working like a charm, thank you very much!

**Comment by digetx** [comment]
Good to know that the HDMI audio problem is resolved, I assume that PR is incoming :)

**Pull request merged**
