### PR TITLE
CI: implement checkpatch.pl

### PR DESCRIPTION
**Pull request by okias**
Signed-off-by: David Heidelberg <david@ixit.cz>

### CODE REVIEW

**Comment by digetx** [comment]
Which cmdline arguments are used for running the checkpatch.pl? Do we use `--strict` option?

**Comment by okias** [comment]
I didn't found, that checkpatch is run with --strict option, do you want it to be run with --strict?

**Comment by digetx** [comment]
Yes, please add --strict.

**Comment by okias** [comment]
@digetx done

**Comment by digetx** [comment]
Very nice, thank you!

**Pull request merged**
