### PR TITLE
Transformer & Chagall updates

### PR DESCRIPTION
**Pull request by maximschwalm**
Add some FIXME tags and fix up device-tree commits

### CODE REVIEW

**Comment by digetx** [comment]
Are those tags really useful? Won't be better to use issue tracker instead of the comments in the code?

**Comment by maximschwalm** [comment]
> Are those tags really useful? Won't be better to use issue tracker instead of the comments in the code?

Yeah, it might be good to use the issue tracker as well. The comments just make the issues more noticable and documentation doesn't hurt IMO. I found other examples like [this](https://github.com/grate-driver/linux/blob/master/arch/arm64/boot/dts/qcom/msm8916-samsung-serranove.dts#L290) one.

**Comment by digetx** [comment]
Well, those comments about downstream kernel aren't appropriate for the upstream. Do you want to have those comments in grate kernel only? The old MMC comment was okay to me.

**Comment by maximschwalm** [comment]
> Well, those comments about downstream kernel aren't appropriate for the upstream. Do you want to have those comments in grate kernel only? The old MMC comment was okay to me.

SDR104 mode works though just not with full clock speed. Is the comment about VIO better now?

**Comment by digetx** [comment]
The VIO comment now is better. I would also replace `Full clock` with `Full 208MHz clock rate` .

**Comment by digetx** [comment]
I'll edit the comments after applying, thanks!

**Pull request merged**
