### PR TITLE
Transformers and Chagall updates

### PR DESCRIPTION
**Pull request by clamor95**
I have included some changes into TF201, TF300T and Chagall device trees. Additionally I've changed commits to co-author system, since this would be the best option. I'd ask you to cherry-pick them instead of current ones in next master branch update. Thanks.

### CODE REVIEW

**Comment by digetx** [comment]
"Co-authored-by" isn't a valid upstream tag, "Co-developed-by" is valid. Otherwise look good at a quick glance.

https://www.kernel.org/doc/html/latest/process/submitting-patches.html#when-to-use-acked-by-cc-and-co-developed-by

**Comment by clamor95** [comment]
"Co-developed-by" does not add few author links as "Co-authored-by"

**Comment by digetx** [comment]
The ""Co-developed-by"" require the "Signed-off-by" tag from each developer.

@osctobe, @cunidev are you okay if we will add yours "Signed-off-by" to the patches?

**Comment by cunidev** [comment]
Yes, sure

**Comment by clamor95** [comment]
Still looks silly

**Comment by digetx** [comment]
@cunidev thanks

The Co-developed-by was correct, I'll re-add after merge. 

@osctobe I'll add yours s-b to the patch, please let me know if you have objections.

**Pull request merged**
