### PR TITLE
WIP: ARM: tegra: chagall fixes

### PR DESCRIPTION
**Pull request by cunidev**
Fix some minor misconfiguration in Pegatron Chagall pinmux

### CODE REVIEW

**Review by digetx — COMMENTED** [review]
Does this mean that Chagall don't have a USB host port? Internet suggests that Chagall only supports USB OTG, is this correct?

**Comment by cunidev** [comment]
Yes. The usb3 bus may be supported through external docks though, which I am not in possession of? 
There is also an usb2 bus that is used by the 3G modem, but this is yet to be enabled due to the need of some specific enable pins.

**Comment by cunidev** [comment]
The strange thing is, enabling usb3 apparently breaks usb1 for some reason.

**Comment by digetx** [comment]
If USB3 physically presents in hardware, but not usable at the moment, then what about to set its `status` to "disabled" and add a comment saying `/* needs a dock station support */` instead of removing the nodes entirely?

**Comment by cunidev** [comment]
Yes. There is also another issue, which I am currently investigating, on the USB bus. I added the WIP tag, please keep on hold for now.

**Comment by digetx** [comment]
Please try to boot with `usbcore.autosuspend=-1` in kernel cmdline and see if it changes anything.

**Comment by cunidev** [comment]
I tried looking deeper, and this MR seems to make more damage than everything so far. I'll close it, and re-open it when I reach a conclusion.

**Pull request closed without merging**
