### PR TITLE
cl2n: correct syntax errors in dts, revert vmmc/vqmmc swap

### PR DESCRIPTION
**Pull request by KaiJan57**
External sd card slot finally works!

### CODE REVIEW

**Comment by digetx** [comment]
Awesome!

**Comment by digetx** [comment]
@KaiJan57 Could you please show `/sys/kernel/debug/tegra_pinmux /sys/kernel/debug/tegra_pinmux_drive` from downstream kernel?

**Comment by KaiJan57** [comment]
[pinmux-ds.txt](https://github.com/grate-driver/linux/files/6289431/pinmux-ds.txt)
Everything in one file. May I ask what you need it for? Just curious. And happy to see others interested in getting that stone age tablet to work :)

**Comment by digetx** [comment]
Needed that for verifying the pinmux in device-tree. I fixed pinmux and also cleaned up other things, everything is pushed to grate-kernel/master, please give it a test and let me know if it works.

**Comment by KaiJan57** [comment]
Most error messages are gone, good job! Please find attached this device-tree's [dmesg boot output](https://github.com/grate-driver/linux/files/6290743/dmesg.txt)(booting arch linux, that's why there is systemd involved).
However, there are a few changes missing I made to my device tree, as the touchscreen node is incomplete; it is should have width and height information. Maybe I can make a PR later.
BTW, do you happen to know how to get that darn BCM4330 chip working?

**Comment by KaiJan57** [comment]
Oh, and another BTW: before your changes there was a peculiarity concerning my device-tree's clock configuration making the tablet freeze without this (`clk_ignore_unused`) kernel parameter. What did you do to fix that? I had spent hours reading through documentation and source code, but to no avail…

**Comment by KaiJan57** [comment]
I just noticed that actual backlight brightness became less linear to setting, probably because you removed calibration data given in downstream kernel.

**Comment by digetx** [comment]
Please always feel free make a PR, I'll merge it and help to complete if needed.
 
For BCM4330 you should try the firmware from the Android ROM, the default upstream one doesn't work well on Nexus 7 for  example. You should also use the NVRAM file from the Android ROM.

I don't recall changing anything specific which could fix clk_ignore_unused, maybe corrected pinmux helped.

I'll add back the original backlight levels on next kernel update, thank you for the feedback!

**Pull request merged**
